language: generic
sudo: required
script: swift test
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: linux
      dist: xenial
      install:
        - wget https://swift.org/builds/swift-4.2.4-release/ubuntu1604/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-ubuntu16.04.tar.gz
        - tar xzf swift-4.2.4-RELEASE-ubuntu16.04.tar.gz
        - export PATH=`pwd`/swift-4.2.4-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
